### ISSUE TITLE
YForm: Medien löschen um den Feldtyp 'imagelist' erweitern

### ISSUE THREAD

**Issue by isospin** [yakamara/yakme#6]
MForm stellt den Feldtypen 'imagelist' zur Verfügung. Dieser wird z.Zt. nicht berücksichtigt sobald Medien gelöscht werden.

**Comment by skerbis** [comment]
Ich denke das sollte mform dann schon selbst liefern. Bitte Issue dort anlegen oder gerne PR

**Comment by tbaddade** [comment]
Ich denke auch das es hier das falsche Repo ist.
